### ISSUE TITLE
TypeError: addtext() takes exactly 3 arguments

### ISSUE THREAD

**Issue by jgphpc** [hpcugent/mympingpong#20] opened 2017-09-02 13:27 UTC
Hi,

* ./mympingponganalysis.py -f ./eff.h5

```
Traceback (most recent call last):
  File "./mympingponganalysis.py", line 310, in <module>
    ppa.plot(go.options.colormap, go.options.input, 
                   go.options.show, go.options.save, lscale, lmask)
  File "./mympingponganalysis.py", line 259, in plot
    self.addtext(self.meta, plt.subplot(gs1[0:1, 5:10]), fig1)
TypeError: addtext() takes exactly 3 arguments (4 given)
```

Quick quickaround is to comment out https://github.com/hpcugent/mympingpong/blob/master/bin/mympingponganalysis.py#L259

Same issue with matplotlib/1.3.1 or matplotlib/2.0.2

**Comment by boegel** [comment] 2017-09-19 12:24
@jgphpc duplicate of #18?

**Comment by jgphpc** [comment] 2017-09-19 14:06
Yes you're right. I guess we can close both now.

**Comment by boegel** [comment] 2017-10-04 11:28
fixed in #21

**Closed as completed by boegel** 2017-10-04 11:28 UTC
